### ISSUE TITLE
Coreos 2079.6.0 package

### ISSUE THREAD

**Issue by nmeylan** [troywilson/coreos-vboxguest-builder#1]
Hello,

First I really appreciate your work. When I found your repo 9 months ago it was like christmas 🎅 .

I got one issue today: the stable version 2079.6.0 was released yesterday but the package is not available [here](https://github.com/troywilson/coreos-vboxguest-builder/releases)
I saw that there is already a tag named [2079.6.0](https://github.com/troywilson/coreos-vboxguest-builder/releases/tag/2079.6.0) that seems to have been created in October 2018, maybe this is the reason why the package has not been uploaded in releases list.

Have a nice day.

**Comment by troywilson** [comment]
Sorry been on hiatus. Looks like there was an error with that release.
